[package]
name = "ru-num"
version = "0.1.0"
authors = ["bda"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
clap = "2.33.0"
